export const EMOJI_LIST = ['😀', '😃', '🤣', '😍', '😘', '🥳', '😻', '😽', '😇', '🦄', '🤓', '😎', '🤩'];
export const TEMP_ERROR_MESSAGE = '일시적인 오류입니다. 다시 시도해주세요.';
export const FILE_TYPE_VALIDATION_ERROR_MESSAGE = 'dropy가 지원하지 않는 파일 형식입니다. 다시 시도해주세요.';
export const CREATING_CHANNEL_MESSAGE = '슬라이드(PDF) 파일 저장 중';
export const NO_EXIST_CHANNEL = '존재하지 않는 채널입니다...';
export const PROGRESS_LAST_MESSAGE = '슬라이드 파일들 업로드 중';
export const NO_EXIST_CHANNEL_MESSAGE = '존재하지 않는 채널입니다...';
export const ENTERING_CHANNEL_MESSAGGGE = '채널 입장중';
export const CODEINPUT_PLACEHOLDER = '채널 코드를 입력해주세요.';
